MOCK_CREATORS = [
    {
        "creatorId": "c1",
        "username": "peemwasu",
        "displayName": "Peem Wasu",
        "platform": "TikTok",
        "profileImageUrl": "https://i.pravatar.cc/150?u=peemwasu",
        "profileUrl": "https://tiktok.com/@peemwasu",
        "followerCount": 4700000,
        "engagementRate": 6.3,
        "categories": ["Entertainment", "Music"],
        "contentStyle": "Lip-sync, Comedy, Dance",
        "audienceInfo": "Female 60%, Gen Z 75%",
        "similarityScore": 92
    },
    {
        "creatorId": "c2",
        "username": "goyyog",
        "displayName": "GoyYog",
        "platform": "Instagram",
        "profileImageUrl": "https://i.pravatar.cc/150?u=goyyog",
        "profileUrl": "https://instagram.com/goyyog",
        "followerCount": 2100000,
        "engagementRate": 4.5,
        "categories": ["Beauty", "Lifestyle"],
        "contentStyle": "Vlog, Review, Fashion",
        "audienceInfo": "Female 80%, Millennials 60%",
        "similarityScore": 79
    },
    {
        "creatorId": "c3",
        "username": "bankthiti",
        "displayName": "Bank Thiti",
        "platform": "Instagram",
        "profileImageUrl": "https://i.pravatar.cc/150?u=bankthiti",
        "profileUrl": "https://instagram.com/bankthiti",
        "followerCount": 3500000,
        "engagementRate": 5.1,
        "categories": ["Lifestyle", "Fitness"],
        "contentStyle": "Workout, Travel, Daily Life",
        "audienceInfo": "Female 65%, Millennials 50%",
        "similarityScore": 65
    },
    {
        "creatorId": "c4",
        "username": "kyutaeoppa",
        "displayName": "Kyutae Oppa",
        "platform": "YouTube",
        "profileImageUrl": "https://i.pravatar.cc/150?u=kyutaeoppa",
        "profileUrl": "https://youtube.com/kyutaeoppa",
        "followerCount": 8200000,
        "engagementRate": 8.2,
        "categories": ["Entertainment", "Food"],
        "contentStyle": "Pranks, Challenge, Mukbang",
        "audienceInfo": "Male 55%, Gen Z 65%",
        "similarityScore": 42
    },
    {
        "creatorId": "c5",
        "username": "pimtha",
        "displayName": "Pimtha",
        "platform": "Instagram",
        "profileImageUrl": "https://i.pravatar.cc/150?u=pimtha",
        "profileUrl": "https://instagram.com/pimtha",
        "followerCount": 4900000,
        "engagementRate": 3.8,
        "categories": ["Beauty", "Fashion", "Travel"],
        "contentStyle": "Photography, Cafe Hopping",
        "audienceInfo": "Female 70%, Millennials 70%",
        "similarityScore": 88
    },
    {
        "creatorId": "c6",
        "username": "bie_the_ska",
        "displayName": "Bie The Ska",
        "platform": "YouTube",
        "profileImageUrl": "https://i.pravatar.cc/150?u=bietheska",
        "profileUrl": "https://youtube.com/bietheska",
        "followerCount": 14000000,
        "engagementRate": 7.5,
        "categories": ["Entertainment", "Comedy"],
        "contentStyle": "Parody, Vlog, Challenge",
        "audienceInfo": "Male 60%, Gen Z 80%",
        "similarityScore": 31
    }
]
