export const MOCK_DASHBOARD_DATA = [
  // Overdue
  {
    id: "d-1",
    briefNo: "BRF-2026-001",
    clientName: "Coca-Cola",
    campaignName: "Summer Refresh",
    briefType: "Ratecard",
    currentStatus: "Waiting Buyer Recap",
    myRole: "Buyer",
    assignee: "Buyer A",
    dueDate: "2026-07-01",
    slaStatus: "Overdue",
    overdueDays: 4,
    lastUpdated: "2026-06-30",
    actionRequired: "Create Recap",
    isCompleted: false,
    route: "/brief/d-1/buyer"
  },
  {
    id: "d-2",
    briefNo: "BRF-2026-002",
    clientName: "Samsung",
    campaignName: "Galaxy Z Fold Launch",
    briefType: "Combined",
    currentStatus: "Waiting Planner Proposal",
    myRole: "Planner",
    assignee: "Planner B",
    dueDate: "2026-07-03",
    slaStatus: "Overdue",
    overdueDays: 2,
    lastUpdated: "2026-07-01",
    actionRequired: "Create Proposal",
    isCompleted: false,
    route: "/brief/d-2/planner"
  },
  // Due Today
  {
    id: "d-3",
    briefNo: "BRF-2026-003",
    clientName: "L'Oréal",
    campaignName: "Paris Skincare",
    briefType: "Standard",
    currentStatus: "Waiting Sales Approval",
    myRole: "Sales",
    assignee: "Sales 1",
    dueDate: "2026-07-05", // Assuming today is 2026-07-05
    slaStatus: "Due Today",
    overdueDays: 0,
    lastUpdated: "2026-07-04",
    actionRequired: "Review Brief",
    isCompleted: false,
    route: "/brief"
  },
  {
    id: "d-4",
    briefNo: "BRF-2026-004",
    clientName: "Nike",
    campaignName: "Air Max Day",
    briefType: "Ratecard",
    currentStatus: "Waiting Buyer Assignment",
    myRole: "Buyer",
    assignee: "Buyer Team",
    dueDate: "2026-07-05",
    slaStatus: "Due Today",
    overdueDays: 0,
    lastUpdated: "2026-07-04",
    actionRequired: "Assign Team",
    isCompleted: false,
    route: "/brief"
  },
  // Waiting for Me (Not due today, but action is with current role)
  {
    id: "d-5",
    briefNo: "BRF-2026-005",
    clientName: "Apple",
    campaignName: "Back to School",
    briefType: "Standard",
    currentStatus: "Waiting Buyer Sourcing",
    myRole: "Buyer",
    assignee: "Buyer A",
    dueDate: "2026-07-08",
    slaStatus: "On Track",
    overdueDays: 0,
    lastUpdated: "2026-07-04",
    actionRequired: "Select Creators",
    isCompleted: false,
    route: "/brief/d-5/buyer"
  },
  {
    id: "d-6",
    briefNo: "BRF-2026-006",
    clientName: "Dyson",
    campaignName: "Airwrap Gen 2",
    briefType: "Combined",
    currentStatus: "Waiting Planner Approval",
    myRole: "Planner",
    assignee: "Planner X",
    dueDate: "2026-07-10",
    slaStatus: "On Track",
    overdueDays: 0,
    lastUpdated: "2026-07-05",
    actionRequired: "Review Proposal",
    isCompleted: false,
    route: "/brief"
  },
  {
    id: "d-7",
    briefNo: "BRF-2026-007",
    clientName: "Toyota",
    campaignName: "Yaris Ativ Gen 3",
    briefType: "Ratecard",
    currentStatus: "Draft",
    myRole: "Sales",
    assignee: "Sales A",
    dueDate: "2026-07-07",
    slaStatus: "On Track",
    overdueDays: 0,
    lastUpdated: "2026-07-05",
    actionRequired: "Submit Brief",
    isCompleted: false,
    route: "/create-brief"
  },
  // Completed
  {
    id: "d-8",
    briefNo: "BRF-2026-008",
    clientName: "Uniqlo",
    campaignName: "Winter Collection",
    briefType: "Standard",
    currentStatus: "Completed",
    myRole: "Planner",
    assignee: "Planner B",
    dueDate: "2026-06-25",
    slaStatus: "On Time",
    overdueDays: 0,
    lastUpdated: "2026-06-25",
    actionRequired: "None",
    isCompleted: true,
    completedDate: "2026-06-24",
    completedAction: "Submitted Proposal",
    route: "/brief"
  },
  {
    id: "d-9",
    briefNo: "BRF-2026-009",
    clientName: "Starbucks",
    campaignName: "Holiday Cups",
    briefType: "Combined",
    currentStatus: "Completed",
    myRole: "Buyer",
    assignee: "Buyer A",
    dueDate: "2026-06-20",
    slaStatus: "Late",
    overdueDays: 2,
    lastUpdated: "2026-06-22",
    actionRequired: "None",
    isCompleted: true,
    completedDate: "2026-06-22",
    completedAction: "Submitted Creators",
    route: "/brief"
  }
];

export const MOCK_SLA_STATS = {
  "Sales": { achievement: 98, total: 45, onTime: 44, late: 1, avgTime: "0.5 days" },
  "Buyer": { achievement: 88, total: 64, onTime: 56, late: 8, avgTime: "2.4 days" },
  "Planner": { achievement: 92, total: 50, onTime: 46, late: 4, avgTime: "3.1 days" },
};
